combat/urls.py
from django.urls import path

from . import views

app_name = 'combat'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('archive/', views.ArchiveView.as_view(), name='archive'),
    path('new/', views.new, name='new'),
    path('<int:character_id>/change/', views.change, name='change'),
    path('add/', views.add, name='add'),
    path('<int:character_id>/delete/', views.delete, name='delete'),
]

inittrackr/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('combat/', include('combat.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

combat/models.py
from django.db import models

class Character(models.Model):
    name = models.CharField(max_length=200)
    perception = models.IntegerField(default=10)
    armorclass = models.IntegerField(default=10)
    hitpoints = models.IntegerField(default=30)
    initiative = models.IntegerField(default=0)
    def __str__(self):
        return self.name

polls/models.py
from django.db import models
from django.utils import timezone

import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

combat/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Character

class IndexView(generic.ListView):
    template_name = 'combat/index.html'
    context_object_name = 'initiative_order'
    def get_queryset(self):
        """Return the party list in initiative order."""
        return Character.objects.filter(hitpoints__gt=0).order_by('-initiative', 'armorclass')

class ArchiveView(generic.ListView):
    template_name = 'combat/archive.html'
    context_object_name = '0hp'
    def get_queryset(self):
        """Return the list of 0hp characters in alphabetical order."""
        return Character.objects.filter(hitpoints=0).order_by('name')

class DetailView(generic.DetailView):
    model = Character
    template_name = 'combat/detail.html'

def new(request):
    template_name = 'combat/new.html'
    return render(request, template_name)

def change(request, character_id):
    character = get_object_or_404(Character, pk=character_id)
    try:
        new_pp = request.POST['perception']
        new_ac = request.POST['armorclass']
        new_hp = request.POST['hitpoints']
        new_in = request.POST['initiative']
    except (KeyError, Character.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'combat/detail.html', {
            'character': character,
            'error_message': "This character does not exist.",
        })
    else:
        character.perception = new_pp
        character.armorclass = new_ac
        character.hitpoints = new_hp
        character.initiative = new_in
        character.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        #return HttpResponseRedirect(reverse('combat:detail', args=(character.id,)))
        return HttpResponseRedirect(reverse('combat:index'))

def add(request):
    new_na = request.POST['name']
    new_pp = request.POST['perception']
    new_ac = request.POST['armorclass']
    new_hp = request.POST['hitpoints']
    new_in = 0 #request.POST['initiative']
    character = Character(name=new_na, perception=new_pp, armorclass=new_ac, hitpoints=new_hp, initiative=new_in)
    character.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    #return HttpResponseRedirect(reverse('combat:detail', args=(character.id,)))
    return HttpResponseRedirect(reverse('combat:index'))

def delete(request, character_id):
    character = get_object_or_404(Character, pk=character_id)
    character.delete()
    return HttpResponseRedirect(reverse('combat:index'))

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Question

# Test 
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

combat/templates/combat/archive.html
{% if 0hp %}
    <ul>
    {% for character in 0hp %}
        <li><a href="{% url 'combat:detail' character.id %}">{{ character.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No characters are in the archive.</p>
{% endif %}

combat/templates/combat/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'combat/style.css' %}">

<h1>{{ character.name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'combat:change' character.id %}" method="post">
{% csrf_token %}
<fieldset>
    <label for="perception">Passive Perception:</label>
    <input type="number" name="perception" id="perception" value="{{ character.perception }}">
    <br>
    <label for="armorclass">Armor Class:</label>
    <input type="number" name="armorclass" id="armorclass" value="{{ character.armorclass }}">
    <br>
    <label for="hitpoints">Hit Points:</label>
    <input type="number" name="hitpoints" id="hitpoints" value="{{ character.hitpoints }}">
    <br>
    <label for="initiative">Initiative:</label>
    <input type="number" name="initiative" id="initiative" value="{{ character.initiative }}">
    <br>
    <input type="submit" name='action' value="Change">
</fieldset>
</form>
<a id="links" href="{% url 'combat:delete' character.id %}">DELETE</a>

combat/templates/combat/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'combat/style.css' %}">

{% if initiative_order %}
    <ul>
    {% for character in initiative_order %}
        <fieldset>
            <legend><a id="character" href="{% url 'combat:detail' character.id %}">{{ character.name }}</a></legend> 
            <ul id="stats">
            <li>AC: {{ character.armorclass }}</li>
            <li>HP: {{ character.hitpoints }}</li>
            <li>IN: {{ character.initiative }}</li>
            <li>PP: {{ character.perception }}</li>
            </ul>
        </fieldset>
    {% endfor %}
    </ul>
{% else %}
    <p>No characters exist.</p>
{% endif %}
<ul id="links">
<li><a id="links" href="{% url 'combat:new' %}">ADD NEW CHARACTER</a></li>
<li><a id="links" href="{% url 'combat:archive' %}">ARCHIVE</a></li>
</ul>

combat/templates/combat/new.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'combat:add' %}" method="post">
{% csrf_token %}
<fieldset>
    <label for="name">Name:</label>
    <input type="text" name="name" id="name">
    <br>
    <label for="perception">Passive Perception:</label>
    <input type="number" name="perception" id="perception" placeholder="10+Perception Modifier" value=10>
    <br>
    <label for="armorclass">Armor Class:</label>
    <input type="number" name="armorclass" id="armorclass" value=10>
    <br>
    <label for="hitpoints">Hit Points:</label>
    <input type="number" name="hitpoints" id="hitpoints" value=0>
    <br>
    <input type="submit" value="Add">
</fieldset>
</form>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>